version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: test_rabbitmq
    ports:
      - 5672:5672
      - 7575:7575
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
